# Generated by Django 2.1.4 on 2019-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='网址')),
                ('key', models.CharField(max_length=128, verbose_name='名称')),
                ('abbreviation', models.CharField(max_length=64, verbose_name='缩写')),
            ],
        ),
    ]
