# Generated by Django 2.1.4 on 2019-03-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicsentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接')),
                ('url_md5', models.CharField(max_length=64, verbose_name='URL哈希化')),
                ('url_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicsentiment.UrlInfo')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='content',
            field=models.ManyToManyField(to='publicsentiment.WenInfo'),
        ),
    ]
