# Generated by Django 2.1.4 on 2019-03-20 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicsentiment', '0002_auto_20190320_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='weninfo',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
