# Generated by Django 2.1.4 on 2019-03-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicsentiment', '0003_weninfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weninfo',
            name='url',
            field=models.CharField(max_length=126, verbose_name='链接'),
        ),
    ]
