# Generated by Django 2.1 on 2018-11-25 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.SmallIntegerField(choices=[(0, '行领导'), (1, '办公室'), (2, '金融管理部'), (3, '国库会计部')], verbose_name='部门')),
                ('head', models.OneToOneField(blank=True, null=True, on_delete='', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
        ),
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_addre', models.CharField(default='app01/file/', max_length=64, verbose_name='文件储存地址')),
                ('file_time', models.CharField(max_length=32, verbose_name='文件日期')),
                ('file_format', models.SmallIntegerField(default=0, verbose_name='文件格式')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.SmallIntegerField(verbose_name='费用标准')),
                ('morning', models.CharField(max_length=32, verbose_name='上午上班')),
                ('noon', models.CharField(max_length=32, verbose_name='上午下班')),
                ('afternoon', models.CharField(max_length=32, verbose_name='下午上班')),
                ('night', models.CharField(max_length=32, verbose_name='下午下班')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lack', models.SmallIntegerField(verbose_name='缺少次数')),
                ('explain', models.TextField(verbose_name='解释说明')),
                ('fine', models.CharField(max_length=64, verbose_name='罚金')),
                ('file_stores_id', models.ForeignKey(on_delete='', to='app01.FileStore')),
                ('user', models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detailed',
            name='file_stores_id',
            field=models.ForeignKey(on_delete='', to='app01.FileStore'),
        ),
        migrations.AddField(
            model_name='detailed',
            name='user',
            field=models.ForeignKey(on_delete='', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department_groups',
            field=models.ForeignKey(on_delete='', to='app01.DepartmentGroup'),
        ),
    ]
