# Generated by Django 2.1 on 2018-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='lack_detail',
            field=models.CharField(max_length=246, verbose_name='缺少详细说明'),
        ),
    ]
