# Generated by Django 2.1 on 2018-11-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department_groups',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='app01.DepartmentGroup'),
        ),
    ]
