# Generated by Django 2.1 on 2018-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentgroup',
            name='department',
            field=models.SmallIntegerField(blank=True, choices=[(0, '行领导'), (1, '办公室'), (2, '金融管理部'), (3, '国库会计部')], null=True, verbose_name='部门'),
        ),
    ]
