# Generated by Django 2.1 on 2018-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181125_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentgroup',
            name='department',
            field=models.CharField(max_length=64, verbose_name='部门'),
        ),
    ]
