# Generated by Django 2.1 on 2018-12-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181204_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': ()},
        ),
    ]
