# Generated by Django 2.1 on 2018-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181125_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailed',
            name='data',
            field=models.CharField(max_length=32, verbose_name='数据日期'),
        ),
        migrations.AlterField(
            model_name='detailed',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
