# Generated by Django 2.1 on 2018-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20181126_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailed',
            name='detai',
            field=models.CharField(default=2, max_length=64, verbose_name='详细'),
            preserve_default=False,
        ),
    ]
