# Generated by Django 2.1 on 2018-11-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20181126_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='go_off_work_time_error',
            field=models.CharField(default=30, max_length=32, verbose_name='下班时间误差'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standard',
            name='go_to_work_time_error',
            field=models.CharField(default=30, max_length=32, verbose_name='上班时间误差'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailed',
            name='file_stores_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.FileStore'),
        ),
    ]
