# Generated by Django 2.1 on 2018-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20181127_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestore',
            name='file_data_summary',
            field=models.BooleanField(default=False, verbose_name='数据汇总'),
        ),
    ]
