# Generated by Django 2.1 on 2018-11-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_filestore_file_data_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailed',
            old_name='detai',
            new_name='detail',
        ),
    ]
