# Generated by Django 2.1.4 on 2018-12-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=248, verbose_name='标题')),
                ('url', models.CharField(max_length=248, verbose_name='链接')),
                ('md5', models.CharField(max_length=128, verbose_name='链接哈希化')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
    ]
