# Generated by Django 2.1 on 2018-12-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=128, verbose_name='根')),
                ('key', models.CharField(max_length=248, verbose_name='提取关键词')),
            ],
        ),
        migrations.AddField(
            model_name='webinfo',
            name='base_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.UrlInfo'),
        ),
    ]
