# Generated by Django 2.1.4 on 2019-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20190228_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
