# Generated by Django 2.1.4 on 2019-03-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20190304_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
